### ISSUE TITLE
normalizeResponse must return a valid JSON API document

### ISSUE THREAD

**Issue by marisawallace** [davidpett/ember-data-contentful#5]
Not sure what I'm doing wrong. I tried to set up this adapter today, and ran into the following error.

I see contentful.js in the stack trace, so I assume the Contentful adapter is being used.

This error is coming from the following call:

```
this.store.findRecord('contentful-module', params.entry_id);
```

I'm using `"ember-data": "2.5.0-beta.3",`.

```
ember.debug.js:28535 Error while processing route: secure.program.entry Assertion Failed: normalizeResponse must return a valid JSON API document:
    * One or more of the following keys must be present: "data", "errors", "meta". Error: Assertion Failed: normalizeResponse must return a valid JSON API document:
    * One or more of the following keys must be present: "data", "errors", "meta".
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26695:21)
    at assert (http://localhost:4200/assets/vendor.js:16535:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:26459:34)
    at assert (http://localhost:4200/assets/vendor.js:126323:37)
    at normalizeResponseHelper (http://localhost:4200/assets/vendor.js:133990:39)
    at http://localhost:4200/assets/vendor.js:133739:98
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10792:25)
    at _adapterRun (http://localhost:4200/assets/vendor.js:135757:31)
    at http://localhost:4200/assets/vendor.js:133738:20logError @ ember.debug.js:28535defaultActionHandlers.error @ ember.debug.js:28478triggerEvent @ ember.debug.js:28594trigger @ ember.debug.js:53473Transition.trigger @ ember.debug.js:53287(anonymous function) @ ember.debug.js:53107tryCatch @ ember.debug.js:53806invokeCallback @ ember.debug.js:53821publish @ ember.debug.js:53789publishRejection @ ember.debug.js:53724(anonymous function) @ ember.debug.js:32054Queue.invoke @ ember.debug.js:333Queue.flush @ ember.debug.js:397DeferredActionQueues.flush @ ember.debug.js:205Backburner.end @ ember.debug.js:560(anonymous function) @ ember.debug.js:1126setTimeout (async)createAutorun @ ember.debug.js:1124Backburner.defer @ ember.debug.js:770(anonymous function) @ ember.debug.js:32050fulfill @ ember.debug.js:53740resolve @ ember.debug.js:53715resolvePromise @ ember.debug.js:53861reader.onload @ fetch.js:105FileReader (async)readBlobAsText @ fetch.js:121Body.text @ fetch.js:195Body.json @ fetch.js:216(anonymous function) @ contentful.js:194tryCatch @ ember.debug.js:53806invokeCallback @ ember.debug.js:53821publish @ ember.debug.js:53789(anonymous function) @ ember.debug.js:32054Queue.invoke @ ember.debug.js:333Queue.flush @ ember.debug.js:397DeferredActionQueues.flush @ ember.debug.js:205Backburner.end @ ember.debug.js:560(anonymous function) @ ember.debug.js:1126setTimeout (async)createAutorun @ ember.debug.js:1124Backburner.defer @ ember.debug.js:770(anonymous function) @ ember.debug.js:32050fulfill @ ember.debug.js:53740handleMaybeThenable @ ember.debug.js:53700resolve @ ember.debug.js:53713resolvePromise @ ember.debug.js:53861xhr.onload @ fetch.js:379XMLHttpRequest.send (async)(anonymous function) @ fetch.js:400initializePromise @ ember.debug.js:53856Promise @ ember.debug.js:55708self.fetch @ fetch.js:343_getContent @ contentful.js:189findRecord @ contentful.js:65_find @ finders.js:24fetchRecord @ store.js:487_fetchRecord @ store.js:548_flushPendingFetchForType @ store.js:594cb @ ember.debug.js:18384OrderedSet.forEach @ ember.debug.js:18187Map.forEach @ ember.debug.js:18392flushAllPendingFetches @ store.js:537Queue.invoke @ ember.debug.js:333Queue.flush @ ember.debug.js:397DeferredActionQueues.flush @ ember.debug.js:205Backburner.end @ ember.debug.js:560Backburner.run @ ember.debug.js:682Backburner.join @ ember.debug.js:702run.join @ ember.debug.js:21181_emberMetalAssign.default.handleEvent @ ember.debug.js:46707exports.default._emberMetalMixin.Mixin.create._Mixin$create.handleEvent @ ember.debug.js:43655exports.default._emberRuntimeSystemObject.default.extend._bubbleEvent @ ember.debug.js:44742(anonymous function) @ ember.debug.js:44684jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
```

**Comment by davidpett** [comment]
Without knowing much of your implementation. Can you check the network tab in dev tools to see if the `fetch` call to contentful goes through? Is your Contententful Content Type `module` or `contentful-module` is your adapter set to use the ContentfulAdapter? If you want to chat, I am usually online in the Ember Slack: https://embercommunity.slack.com/team/davidpett

**Comment by marisawallace** [comment]
I took another crack at this, and I'm no longer seeing the issue.

I think the problem was my adapter setup:

`app/adapters/contentful-module.js`:

```
import ContentfulAdapter from './contentful';

export default ContentfulAdapter.extend({
});
```

`app/adapters/contentful.js`:

```
import ContentfulAdapter from 'ember-data-contentful/adapters/contentful';

export default ContentfulAdapter.extend({

});
```

---

Changing it to:

`app/adapters/contentful-module.js`:

```
+import ContentfulAdapter from 'ember-data-contentful/adapters/contentful';
+
+export default ContentfulAdapter.extend({
+});
```

Seems to have fixed the issue. I'm not sure why.

@davidpett thanks for the addon!
